import matplotlib.pyplot as plt
from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas
from PyQt5 import QtCore, QtGui, QtWidgets


class FeatureCraft_Ui(object):
    def setupUi(self, FeatureCraft):
        FeatureCraft.setObjectName("FeatureCraft")
        FeatureCraft.resize(1280, 720)
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(12)
        FeatureCraft.setFont(font)
        self.centralwidget = QtWidgets.QWidget(FeatureCraft)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.verticalLayout_2.addWidget(self.tabWidget)
        FeatureCraft.setCentralWidget(self.centralwidget)

        self.setup_sift_tab()
        self.setup_corner_detection_tab()
        self.setup_sift_output_tab()

        ## Menu Bar
        self.menubar = QtWidgets.QMenuBar(FeatureCraft)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1101, 28))
        self.menubar.setObjectName("menubar")
        FeatureCraft.setMenuBar(self.menubar)

        ## Status Bar
        self.statusbar = QtWidgets.QStatusBar(FeatureCraft)
        self.statusbar.setObjectName("statusbar")
        FeatureCraft.setStatusBar(self.statusbar)

        ### File Menu
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menubar.addAction(self.menuFile.menuAction())
        #### Load Image
        self.actionImport_Image = QtWidgets.QAction(FeatureCraft)
        self.actionImport_Image.setShortcut("Ctrl+I")
        self.actionImport_Image.setObjectName("actionLoad_Image")
        self.menuFile.addAction(self.actionImport_Image)
        #### Exit app
        self.actionExit = QtWidgets.QAction(FeatureCraft)
        self.actionExit.setObjectName("actionExit")
        self.actionExit.setShortcut("Ctrl+Q")
        self.actionExit.triggered.connect(self.exit_application)
        self.menuFile.addAction(self.actionExit)

        ## Harris Canvas
        self.harris_input_vlayout = QtWidgets.QHBoxLayout(self.left_widget_corner_tab)
        self.harris_input_vlayout.setObjectName("harris_input_hlayout")
        self.harris_input_figure = plt.figure()
        self.harris_input_figure_canvas = FigureCanvas(self.harris_input_figure)
        self.harris_input_vlayout.addWidget(self.harris_input_figure_canvas)
        ## Harris Output
        self.harris_output_vlayout = QtWidgets.QHBoxLayout(self.right_widget_corner_tab)
        self.harris_output_vlayout.setObjectName("harris_output_hlayout")
        self.harris_output_figure = plt.figure()
        self.harris_output_figure_canvas = FigureCanvas(self.harris_output_figure)
        self.harris_output_vlayout.addWidget(self.harris_output_figure_canvas)
        ## End of Harris canvas

        ## SIFT 1
        self.sift_target_hlayout = QtWidgets.QHBoxLayout(self.sift_target_image)
        self.sift_target_hlayout.setObjectName("sift_target_hlayout")
        self.sift_target_figure = plt.figure()
        self.sift_target_figure_canvas = FigureCanvas(self.sift_target_figure)
        self.sift_target_hlayout.addWidget(self.sift_target_figure_canvas)
        ## SIFT 2
        self.sift_template_hlayout = QtWidgets.QHBoxLayout(self.sift_template_image)
        self.sift_template_hlayout.setObjectName("sift_template_hlayout")
        self.sift_template_figure = plt.figure()
        self.sift_template_figure_canvas = FigureCanvas(self.sift_template_figure)
        self.sift_template_hlayout.addWidget(self.sift_template_figure_canvas)
        ## SIFT output
        self.sift_output_hlayout = QtWidgets.QHBoxLayout(self.sift_output)
        self.sift_output_hlayout.setObjectName("sift_output_hlayout")
        self.sift_output_figure = plt.figure()
        self.sift_output_figure_canvas = FigureCanvas(self.sift_output_figure)
        self.sift_output_hlayout.addWidget(self.sift_output_figure_canvas)
        ## End of SIFT canvas

        self.retranslateUi(FeatureCraft)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(FeatureCraft)

    def setup_sift_tab(self):
        self.sift_tab = QtWidgets.QWidget()
        self.sift_tab.setObjectName("sift_tab")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.sift_tab)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.left_widget_corner_tab = QtWidgets.QWidget(self.sift_tab)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.left_widget_corner_tab.sizePolicy().hasHeightForWidth()
        )
        self.left_widget_corner_tab.setSizePolicy(sizePolicy)
        self.left_widget_corner_tab.setObjectName("left_widget_corner_tab")
        self.horizontalLayout_3.addWidget(self.left_widget_corner_tab)
        self.right_widget_corner_tab = QtWidgets.QWidget(self.sift_tab)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.right_widget_corner_tab.sizePolicy().hasHeightForWidth()
        )
        self.right_widget_corner_tab.setSizePolicy(sizePolicy)
        self.right_widget_corner_tab.setObjectName("right_widget_corner_tab")
        self.horizontalLayout_3.addWidget(self.right_widget_corner_tab)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.consumed_time_label = QtWidgets.QLabel(self.sift_tab)
        self.consumed_time_label.setObjectName("consumed_time_label")
        self.horizontalLayout.addWidget(self.consumed_time_label)
        self.threshold_label = QtWidgets.QLabel(self.sift_tab)
        self.threshold_label.setObjectName("threshold_label")
        self.horizontalLayout.addWidget(self.threshold_label)
        self.horizontalSlider_corner_tab = QtWidgets.QSlider(self.sift_tab)
        self.horizontalSlider_corner_tab.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_corner_tab.setObjectName("horizontalSlider_corner_tab")
        self.horizontalLayout.addWidget(self.horizontalSlider_corner_tab)
        self.threshold_value_label = QtWidgets.QLabel(self.sift_tab)
        self.threshold_value_label.setText("")
        self.threshold_value_label.setObjectName("threshold_value_label")
        self.horizontalLayout.addWidget(self.threshold_value_label)
        spacerItem = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout.addItem(spacerItem)
        self.apply_harris_push_button = QtWidgets.QPushButton(self.sift_tab)
        self.apply_harris_push_button.setObjectName("apply_harris_push_button")
        self.horizontalLayout.addWidget(self.apply_harris_push_button)
        self.apply_lambda_minus_push_button = QtWidgets.QPushButton(self.sift_tab)
        self.apply_lambda_minus_push_button.setObjectName(
            "apply_lambda_minus_push_button"
        )
        self.horizontalLayout.addWidget(self.apply_lambda_minus_push_button)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.tabWidget.addTab(self.sift_tab, "")

    def setup_sift_output_tab(self):
        self.setup_sift_output_tab = QtWidgets.QWidget()
        self.setup_sift_output_tab.setObjectName("tab_3")
        self.gridLayout = QtWidgets.QGridLayout(self.setup_sift_output_tab)
        self.gridLayout.setObjectName("gridLayout")
        self.sift_output = QtWidgets.QFrame(self.setup_sift_output_tab)
        self.sift_output.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.sift_output.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sift_output.setObjectName("output_image_sift")
        self.gridLayout.addWidget(self.sift_output, 0, 0, 1, 1)
        self.tabWidget.addTab(self.setup_sift_output_tab, "")

    def setup_corner_detection_tab(self):
        self.corner_detection_tab = QtWidgets.QWidget()
        self.corner_detection_tab.setObjectName("tab")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.corner_detection_tab)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.sift_target_image = QtWidgets.QFrame(self.corner_detection_tab)
        self.sift_target_image.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.sift_target_image.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sift_target_image.setObjectName("input_image_1_sift")

        self.horizontalLayout_12.addWidget(self.sift_target_image)
        self.sift_template_image = QtWidgets.QFrame(self.corner_detection_tab)
        self.sift_template_image.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.sift_template_image.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sift_template_image.setObjectName("input_image_2_sift")
        self.horizontalLayout_12.addWidget(self.sift_template_image)
        self.verticalLayout_4.addLayout(self.horizontalLayout_12)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.n_octaves = QtWidgets.QLabel(self.corner_detection_tab)
        self.n_octaves.setObjectName("n_octaves")
        self.horizontalLayout_8.addWidget(self.n_octaves)
        self.n_octaves_spin_box = QtWidgets.QSpinBox(self.corner_detection_tab)
        self.n_octaves_spin_box.setObjectName("n_octaves_spin_box")
        self.n_octaves_spin_box.setValue(4)
        self.n_octaves_spin_box.setSingleStep(1)
        self.n_octaves_spin_box.setMinimum(4)
        self.n_octaves_spin_box.setMaximum(8)
        self.horizontalLayout_8.addWidget(self.n_octaves_spin_box)
        self.horizontalLayout_10.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.s_value = QtWidgets.QLabel(self.corner_detection_tab)
        self.s_value.setObjectName("s_value")
        self.horizontalLayout_9.addWidget(self.s_value)
        self.s_value_spin_box = QtWidgets.QSpinBox(self.corner_detection_tab)
        self.s_value_spin_box.setObjectName("s_value_spin_box")
        self.s_value_spin_box.setValue(2)
        self.s_value_spin_box.setSingleStep(1)
        self.s_value_spin_box.setMinimum(2)
        self.s_value_spin_box.setMaximum(5)
        self.horizontalLayout_9.addWidget(self.s_value_spin_box)
        self.horizontalLayout_10.addLayout(self.horizontalLayout_9)
        self.verticalLayout_3.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.sigma_base = QtWidgets.QLabel(self.corner_detection_tab)
        self.sigma_base.setObjectName("sigma_base")
        self.horizontalLayout_7.addWidget(self.sigma_base)
        self.sigma_base_spin_box = QtWidgets.QDoubleSpinBox(self.corner_detection_tab)
        self.sigma_base_spin_box.setObjectName("sigma_base_spin_box")
        self.sigma_base_spin_box.setValue(1.6)
        self.sigma_base_spin_box.setSingleStep(0.1)
        self.sigma_base_spin_box.setMinimum(1.6)
        self.sigma_base_spin_box.setMaximum(3)
        self.horizontalLayout_7.addWidget(self.sigma_base_spin_box)
        self.horizontalLayout_11.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.r_ratio = QtWidgets.QLabel(self.corner_detection_tab)
        self.r_ratio.setObjectName("r_ratio")
        self.horizontalLayout_6.addWidget(self.r_ratio)
        self.r_ratio_spin_box = QtWidgets.QDoubleSpinBox(self.corner_detection_tab)
        self.r_ratio_spin_box.setObjectName("r_ratio_spin_box")
        self.r_ratio_spin_box.setValue(10)
        self.r_ratio_spin_box.setSingleStep(1)
        self.r_ratio_spin_box.setMinimum(6)
        self.r_ratio_spin_box.setMaximum(12)
        self.horizontalLayout_6.addWidget(self.r_ratio_spin_box)
        self.horizontalLayout_11.addLayout(self.horizontalLayout_6)
        self.verticalLayout_3.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.contrast_th = QtWidgets.QLabel(self.corner_detection_tab)
        self.contrast_th.setObjectName("contrast_th")
        self.horizontalLayout_4.addWidget(self.contrast_th)
        self.contrast_th_slider = QtWidgets.QSlider(self.corner_detection_tab)
        self.contrast_th_slider.setOrientation(QtCore.Qt.Horizontal)
        self.contrast_th_slider.setObjectName("contrast_th_slider")
        self.contrast_th_slider.setValue(30)
        self.contrast_th_slider.setSingleStep(10)
        self.contrast_th_slider.setMinimum(1)
        self.contrast_th_slider.setMaximum(100)
        self.horizontalLayout_4.addWidget(self.contrast_th_slider)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.confusion_factor = QtWidgets.QLabel(self.corner_detection_tab)
        self.confusion_factor.setObjectName("confusion_factor")
        self.horizontalLayout_2.addWidget(self.confusion_factor)
        self.confusion_factor_slider = QtWidgets.QSlider(self.corner_detection_tab)
        self.confusion_factor_slider.setOrientation(QtCore.Qt.Horizontal)
        self.confusion_factor_slider.setObjectName("confusion_factor_slider")
        self.confusion_factor_slider.setValue(3)
        self.confusion_factor_slider.setSingleStep(1)
        self.confusion_factor_slider.setMinimum(1)
        self.confusion_factor_slider.setMaximum(10)
        self.horizontalLayout_2.addWidget(self.confusion_factor_slider)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.sift_elapsed_time = QtWidgets.QLabel(self.corner_detection_tab)
        self.sift_elapsed_time.setMinimumSize(QtCore.QSize(0, 25))
        self.sift_elapsed_time.setMaximumSize(QtCore.QSize(16777215, 25))
        self.sift_elapsed_time.setObjectName("label")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        spacerItem1 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout_13.addItem(spacerItem1)
        self.apply_sift_vlayout = QtWidgets.QVBoxLayout()
        self.apply_sift_vlayout.setObjectName("apply_sift_vlayout")
        self.apply_sift = QtWidgets.QPushButton(self.corner_detection_tab)
        self.apply_sift.setObjectName("pushButton")
        self.apply_sift_vlayout.addWidget(self.apply_sift)
        self.apply_sift_vlayout.addWidget(self.sift_elapsed_time)
        self.horizontalLayout_13.addLayout(self.apply_sift_vlayout)
        spacerItem2 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout_13.addItem(spacerItem2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_13)
        self.tabWidget.addTab(self.corner_detection_tab, "")

    def exit_application(self):
        sys.exit()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.consumed_time_label.setText(
            _translate("MainWindow", "This Operation consumed ..... seconds || ")
        )
        self.threshold_label.setText(_translate("MainWindow", "Adjust the threshold"))
        self.apply_harris_push_button.setText(_translate("MainWindow", "Apply Harris"))
        self.apply_lambda_minus_push_button.setText(
            _translate("MainWindow", "Apply lambda minus")
        )
        self.tabWidget.setTabText(
            self.tabWidget.indexOf(self.sift_tab),
            _translate("MainWindow", "Corner Detection"),
        )
        self.n_octaves.setText(_translate("MainWindow", "n_octaves: 4"))
        self.s_value.setText(_translate("MainWindow", "s_value: 2"))
        self.sigma_base.setText(_translate("MainWindow", "sigma_base: 1.6"))
        self.r_ratio.setText(_translate("MainWindow", "r_ratio: 10"))
        self.contrast_th.setText(_translate("MainWindow", "contrast_th: 0.03"))
        self.confusion_factor.setText(_translate("MainWindow", "confusion_factor: 0.3"))
        self.sift_elapsed_time.setText(_translate("MainWindow", "Elapsed Time is"))
        self.apply_sift.setText(_translate("MainWindow", "Apply SIFT"))
        self.tabWidget.setTabText(
            self.tabWidget.indexOf(self.corner_detection_tab),
            _translate("MainWindow", "SIFT"),
        )
        self.tabWidget.setTabText(
            self.tabWidget.indexOf(self.setup_sift_output_tab),
            _translate("MainWindow", "SIFT Output"),
        )

        font_global_thresholds_label = QtGui.QFont()
        font_global_thresholds_label.setPointSize(14)
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionImport_Image.setText(_translate("MainWindow", "Import Image"))
        self.actionExit.setText(_translate("MainWindow", "Exit app"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = FeatureCraft_Ui()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
