# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'task3_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1101, 732)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.left_widget_corner_tab = QtWidgets.QWidget(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.left_widget_corner_tab.sizePolicy().hasHeightForWidth())
        self.left_widget_corner_tab.setSizePolicy(sizePolicy)
        self.left_widget_corner_tab.setObjectName("left_widget_corner_tab")
        self.horizontalLayout_3.addWidget(self.left_widget_corner_tab)
        self.right_widget_corner_tab = QtWidgets.QWidget(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.right_widget_corner_tab.sizePolicy().hasHeightForWidth())
        self.right_widget_corner_tab.setSizePolicy(sizePolicy)
        self.right_widget_corner_tab.setObjectName("right_widget_corner_tab")
        self.horizontalLayout_3.addWidget(self.right_widget_corner_tab)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.consumed_time_label = QtWidgets.QLabel(self.tab_2)
        self.consumed_time_label.setObjectName("consumed_time_label")
        self.horizontalLayout.addWidget(self.consumed_time_label)
        self.threshold_label = QtWidgets.QLabel(self.tab_2)
        self.threshold_label.setObjectName("threshold_label")
        self.horizontalLayout.addWidget(self.threshold_label)
        self.horizontalSlider_corner_tab = QtWidgets.QSlider(self.tab_2)
        self.horizontalSlider_corner_tab.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_corner_tab.setObjectName("horizontalSlider_corner_tab")
        self.horizontalLayout.addWidget(self.horizontalSlider_corner_tab)
        self.threshold_value_label = QtWidgets.QLabel(self.tab_2)
        self.threshold_value_label.setText("")
        self.threshold_value_label.setObjectName("threshold_value_label")
        self.horizontalLayout.addWidget(self.threshold_value_label)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.apply_harris_push_button = QtWidgets.QPushButton(self.tab_2)
        self.apply_harris_push_button.setObjectName("apply_harris_push_button")
        self.horizontalLayout.addWidget(self.apply_harris_push_button)
        self.apply_lambda_minus_push_button = QtWidgets.QPushButton(self.tab_2)
        self.apply_lambda_minus_push_button.setObjectName("apply_lambda_minus_push_button")
        self.horizontalLayout.addWidget(self.apply_lambda_minus_push_button)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tabWidget.addTab(self.tab, "")
        self.verticalLayout_2.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1101, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionLoad_Image = QtWidgets.QAction(MainWindow)
        self.actionLoad_Image.setObjectName("actionLoad_Image")
        self.menuFile.addAction(self.actionLoad_Image)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.consumed_time_label.setText(_translate("MainWindow", "This Operation consumed ..... seconds || "))
        self.threshold_label.setText(_translate("MainWindow", "Adjust the threshold"))
        self.apply_harris_push_button.setText(_translate("MainWindow", "Apply Harris"))
        self.apply_lambda_minus_push_button.setText(_translate("MainWindow", "Apply lambda minus"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Corner Detection"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Sift"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionLoad_Image.setText(_translate("MainWindow", "Load Image"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
